version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: macropolis-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:80